apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
  labels:
    name: prometheus

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
  namespace: prometheus

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pods-get-list-watch
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-pods-get-list-watch
subjects:
  - kind: Group
    name: system:serviceaccounts:prometheus
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pods-get-list-watch
  apiGroup: rbac.authorization.k8s.io
