apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dave

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: task01
subjects:
  - kind: ServiceAccount
    name: bob
    namespace: "*"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
