# Vanilla nginx alpine
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: web
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine3.17
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: stub-status
      volumes:
        - name: stub-status
          configMap:
            name: stub-conf
            items:
              - key: stub.conf
                path: stub.conf

---
#Config map with stub-status page
apiVersion: v1
kind: ConfigMap
metadata:
  name: stub-conf
data:
  stub.conf: |
    server {
      listen       80;
      server_name  localhost;
      location /basic_status {
        stub_status;
      }
    }

---
# Service for nginx
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: exporter
spec:
  selector:
    app: web
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# Prometheus custom node exporter pod
apiVersion: v1
kind: Pod
metadata:
  name: nginx-exporter
  labels:
    app: exporter
spec:
  containers:
    - name: nginx-exporter
      image: nginx/nginx-prometheus-exporter:latest
      args: ["-nginx.scrape-uri=http://web-service/basic_status"]

---
#Service for nginx exporter
apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter-service
spec:
  selector:
    app: exporter
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9113
      targetPort: 9113
      name: metrics

---
#Service Monitor for nginx
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-app
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: exporter
  endpoints:
    - port: metrics