sudo: required

language: go

services:
  - docker

go:  
  - "1.10.1"

before_install:  
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - export VER=`grep "const version = " cmd/netperf-operator/main.go | cut -f2 -d'"'`
  - export GIT=`git rev-parse --short HEAD`
  - CGO_ENABLED=0 GOOS=linux go build -o netperf-operator -ldflags "-X main.VersionString=v${VER}-${GIT}" cmd/netperf-operator/main.go
  - docker build -t tailoredcloud/netperf-operator:v${VER}-${GIT} .

deploy:
  provider: script
  script: bash docker_push.sh
  