helmDefaults:
  wait: true
  verify: false

repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: chartmuseum
    url: https://chartmuseum.github.io/charts

releases:
  - name: nginx-ingress
    namespace: nginx-ingress
    chart: ingress-nginx/ingress-nginx
    needs:
      - cert-manager/cert-manager
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    set:
      - name: installCRDs
        value: true
    values:
      - resources:
          - apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: letsencrypt-production
            spec:
              acme:
                server: https://acme-v02.api.letsencrypt.org/directory
                email: ab@it-grad.ru
                privateKeySecretRef:
                  name: chartmuseum.158.160.63.42.nip.io
                solvers:
                  - http01:
                      ingress:
                        ingressClassName: nginx
  - name: chartmuseum
    namespace: chartmuseum
    chart: chartmuseum/chartmuseum
    needs:
      - nginx-ingress/nginx-ingress
    values:
      - cm-values.yaml