apiVersion: v1
kind: Secret
metadata:
  name: minio-access
type: Opaque
stringData:
  key: minio

---

apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  key: minio123
