apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: my-pod
spec:
  containers:
    - name: web
      image: aablago4/nginx_custom:1.0
      volumeMounts:
        - name: app
          mountPath: /app
        - name: local
          mountPath: "/app/data"
  volumes:
    - name: app
      emptyDir: { }
    - name: local
      persistentVolumeClaim:
        claimName: my-pvc
  initContainers:
    - name: init-web01
      image: busybox:1.31
      command: [ 'sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh' ]
      volumeMounts:
        - name: app
          mountPath: /app
